# this code belongs to https://www.codedex.io/python/05-snail-mail

print('+---------------------------------------------------------------------+')
print('|                                                        August 2023  |')
print('|                                                       Brighton, UK  |')
print('|  Dear Me,                                                           |')
print('|                                                                     |')
print('|      Believe in yourself and work hard for your dreams.             |')
print('|      Keep coding to build a strong foundation for your future.      |')
print('|      Also, maybe study a bit more so you can graduate with          |')
print('|      honors and get a good career (hopefully in IT hahaha).         |')
print('|      You can, and you will, remember that                           |')
print('|                                                                     |')
print('|                                              Safiya                 |')
print('|                                                                     |')
print('+---------------------------------------------------------------------+')